name: Test schedule event

on:
  schedule:
    - cron: '* * * * *'
    - iso: '2023-05-19 17:45'
      timezone: Europe/Brussels

jobs:
  test-schedule:
    runs-on: ubuntu:latest
    steps:
      - name: print time
        run: ['echo', '${{ schedule["iso"] }}']
