name: Example SSE event workflow

on:
  sse:
    stream: https://stream.wikimedia.org/v2/stream/mediawiki.recentchange
    format: json
    filter:
      -
        - 'sse["type"] == "edit"'
        - 'sse["wiki"] == "mediawikiwiki"'

jobs:
  test-sse:
    runs-on: ubuntu:latest
    steps:
      - name: print title
        run: ['echo', '${{ sse["title"] }}']
